.PHONY: check

install:
	/usr/bin/install -d $(DESTDIR)/usr/share/documentdb/scripts/
	/usr/bin/install -m 644 emulator_entrypoint.sh $(DESTDIR)/usr/share/documentdb/scripts/emulator_entrypoint.sh
	/usr/bin/install -m 644 init_documentdb_data.sh $(DESTDIR)/usr/share/documentdb/scripts/init_documentdb_data.sh

check:
