.PHONY: check

install:
	/usr/bin/install -d $(DESTDIR)/usr/share/documentdb/scripts/
	/usr/bin/install -m 644 utils.sh $(DESTDIR)/usr/share/documentdb/scripts/utils.sh
	/usr/bin/install -m 644 start_oss_server.sh $(DESTDIR)/usr/share/documentdb/scripts/start_oss_server.sh
	/usr/bin/install -m 644 build_and_start_gateway.sh $(DESTDIR)/usr/share/documentdb/scripts/build_and_start_gateway.sh
	/usr/bin/install -m 644 setup_psqlrc.sh $(DESTDIR)/usr/share/documentdb/scripts/setup_psqlrc.sh

check:

