.PHONY: check

install:
	/usr/bin/install -d $(DESTDIR)/usr/share/documentdb/sample-data/
	/usr/bin/install -m 644 01-users.js $(DESTDIR)/usr/share/documentdb/sample-data/01-users.js
	/usr/bin/install -m 644 02-products.js $(DESTDIR)/usr/share/documentdb/sample-data/02-products.js
	/usr/bin/install -m 644 03-orders.js $(DESTDIR)/usr/share/documentdb/sample-data/03-orders.js
	/usr/bin/install -m 644 04-analytics.js $(DESTDIR)/usr/share/documentdb/sample-data/04-analytics.js
	/usr/bin/install -m 644 README.md $(DESTDIR)/usr/share/documentdb/sample-data/README.md

check:
